// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CreateRepository
  static let CreateRepositoryPayload = ApolloAPI.Object(
    typename: "CreateRepositoryPayload",
    implementedInterfaces: []
  )
}